services:
  postgres:
    image: postgres:15-alpine
    container_name: portfolio_postgres
    environment:
      POSTGRES_DB: portfolio_analyzer
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: portfolio_redis
    command: redis-server --requirepass redis_pass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: portfolio_backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://portfolio_user:portfolio_pass@postgres:5432/portfolio_analyzer
      - REDIS_URL=redis://:redis_pass@redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules

  ml-service:
    build: ./ml-service
    container_name: portfolio_ml_service
    ports:
      - "8002:8002"
    volumes:
      - ./ml-service:/app

volumes:
  postgres_data:
  redis_data:
